language: node_js
node_js:
- '10'
env:
- NODE_ENV=test
before_script:
- npm install -D
script:
- npm run build
- npm run coverage
- rm -rf test/dump
deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: npm
  email: 'dhkatz.16@gmail.com'
  api_key:
    secure: ioX3IL8GUyF24yTDgVNlHasR6mDwGiOJN4D1RqFibKAnd8gGFU7Lfrl4MVfVQ3HVUdNafxmUz/6Vd9xpgP5w9DScJfPg9DVdWZ+6RmCKwM23b7a/84PZJtjGzMuyVZQ1CxDN6acvJbaQovcj6phcPdaCL7TwJjWVtJVP7aVHsgFahytMlQXFeZyDou4xE+f7xEGHogS+dI6tUAFnXiKSVtGaLjHoMOI/GDVYZ+2q7lYUD/RghZlPdPXi9scP+iSdciW5ZXCDyrSeodzPJallG7Y1aNNAyKUTRrY8LN9X0TxbIfmyDIzh6VmJDUOTLuUMrKx6YLp5DnviV7U2F35iZLL7t+CdbO0XJ8qwW6Mn2usw/kjuPvXe9i6K+y/03qceesoz33o24n6n0sjE5gCqtbuzOU+1SkpoS8V25e2jU9fOnhxqnwvUrgZlhm1mWyR8Rp8xpeZjfDy1W4GG2XKl6oElYw1xHsyHADSA7xTiMdkk4tCrzZjM5ZBphtco76f/AS4Z68931ybLP859xwix6gx6YZMKrLA19EaJKy91S9nXMejReZsRyumapPa3dUacH9zZXZ8mDYVzIzuiiu60N/UU7sN2og/eGiad0sargrsxEa3OWpj0l+yD0cxsmH38fo4xAenGsqPjqE1nV/UOaGuleRwLjSZ9KF9nBLxjQl8=
